import {
  AppointmentRequest,
  CalendarEvent,
  Customer,
  Employee,
  Resource,
  ServiceItem,
  CompanySettingsData,
  BookingHoursDay,
  ShiftEntry,
} from './types';

export const initialAppointmentRequests: AppointmentRequest[] = [
  {
    id: 'req-1',
    customerName: 'Nilufar Ismayilova',
    serviceName: 'Sample Service',
    dateStr: '1 October 2026',
    timeStr: '10:00 - 10:30',
    timeAgo: '10 minutes ago',
    staffName: 'Eloise Denniese',
    channel: 'WhatsApp',
    status: 'pending',
  },
  {
    id: 'req-2',
    customerName: 'Atilla Ismayilova',
    serviceName: 'Sample Service',
    dateStr: '1 October 2026',
    timeStr: '11:00 - 11:30',
    timeAgo: '1 minutes ago',
    staffName: 'Nilufar Ismayilova',
    channel: 'Instagram',
    status: 'pending',
  },
];

export const initialCalendarEvents: CalendarEvent[] = [
  {
    id: 'cal-1',
    customerName: 'Nilufar Ismayilova',
    serviceName: 'Sample Service',
    staffName: 'Eloise Denniese',
    day: 'wed',
    dateDisplay: 'Wed 07/10',
    startTime: '10:00',
    endTime: '10:30',
    colorTheme: 'yellow',
  },
  {
    id: 'cal-2',
    customerName: 'Marie Dupont',
    serviceName: 'Haircut',
    staffName: 'Nilufar Ismayilova',
    day: 'thu',
    dateDisplay: 'Thu 08/10',
    startTime: '13:30',
    endTime: '14:00',
    colorTheme: 'purple',
    isAiBooked: true,
  },
  {
    id: 'cal-3',
    customerName: 'L\u00e9a Girard',
    serviceName: 'Colouring',
    staffName: 'Eloise Denniese',
    day: 'fri',
    dateDisplay: 'Fri 09/10',
    startTime: '11:00',
    endTime: '12:30',
    colorTheme: 'green',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Nilufar Ismayilova',
    initials: 'NI',
    email: 'nilufar.demo@example.ch',
    phone: '+41 78 555 00 19',
    language: 'EN',
    lastBooking: 'Thu 1 Oct, 10:30',
    bookingsCount: 3,
  },
  {
    id: 'cust-2',
    name: 'Marie Dupont',
    initials: 'MD',
    email: 'marie.dupont@example.ch',
    phone: '+41 79 555 01 12',
    language: 'FR',
    lastBooking: 'Wed 30 Sep, 13:30',
    bookingsCount: 2,
  },
  {
    id: 'cust-3',
    name: 'L\u00e9a Girard',
    initials: 'LG',
    email: 'lea.girard@example.ch',
    phone: '+41 76 555 02 34',
    language: 'FR',
    lastBooking: 'Mon 28 Sep, 16:00',
    bookingsCount: 1,
  },
  {
    id: 'cust-4',
    name: 'Chlo\u00e9 Favre',
    initials: 'CF',
    email: 'chloe.favre@example.ch',
    phone: '+41 77 555 03 45',
    language: 'DE',
    lastBooking: 'Fri 25 Sep, 10:00',
    bookingsCount: 1,
  },
];

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    firstName: 'Nilufar',
    lastName: 'Ismayilova',
    name: 'Nilufar Ismayilova',
    initials: 'NI',
    email: 'nilufar.demo@example.ch',
    phone: '+41 78 555 00 19',
    status: 'Active',
    location: 'Bella Hair Salon',
    canBookOnline: true,
    hidden: false,
  },
  {
    id: 'emp-2',
    firstName: 'Eloise',
    lastName: 'Denniese',
    name: 'Eloise Denniese',
    initials: 'ED',
    email: 'eloise.denniese@example.ch',
    phone: '+41 79 555 04 56',
    status: 'Active',
    location: 'Bella Hair Salon',
    canBookOnline: true,
    hidden: false,
  },
];

export const initialServices: ServiceItem[] = [
  {
    id: 'srv-1',
    name: 'Sample Service',
    durationMinutes: 30,
    priceCHF: 45.0,
    onlineBooking: true,
    assignedEmployeesCount: 1,
    category: 'Hair',
    description: 'Quick hair styling and consultation for regular care.',
  },
  {
    id: 'srv-2',
    name: 'Haircut',
    durationMinutes: 30,
    priceCHF: 55.0,
    onlineBooking: true,
    assignedEmployeesCount: 2,
    category: 'Haircut',
    description: 'Precision haircut including shampoo, conditioning, and blow dry.',
  },
  {
    id: 'srv-3',
    name: 'Colouring',
    durationMinutes: 90,
    priceCHF: 120.0,
    onlineBooking: false,
    assignedEmployeesCount: 1,
    category: 'Colour',
    description: 'Full hair colouring and gloss treatment by experienced colorists.',
  },
];

export const initialResources: Resource[] = [];

export const initialShiftOverview: ShiftEntry[] = [
  {
    employeeId: 'emp-1',
    employeeName: 'Nilufar Ismayilova',
    initials: 'NI',
    avatarColor: 'bg-rose-100 text-rose-700',
    shifts: {
      'Mon 05 Oct': { start: '09:00', end: '18:00' },
      'Tue 06 Oct': { start: '09:00', end: '18:00' },
      'Wed 07 Oct': { start: '09:00', end: '18:00' },
      'Thu 08 Oct': { start: '09:00', end: '18:00' },
      'Fri 09 Oct': { start: '09:00', end: '18:00' },
      'Sat 10 Oct': null,
      'Sun 11 Oct': null,
    },
  },
  {
    employeeId: 'emp-2',
    employeeName: 'Eloise Denniese',
    initials: 'ED',
    avatarColor: 'bg-amber-100 text-amber-700',
    shifts: {
      'Mon 05 Oct': null,
      'Tue 06 Oct': null,
      'Wed 07 Oct': { start: '10:00', end: '18:00' },
      'Thu 08 Oct': { start: '10:00', end: '18:00' },
      'Fri 09 Oct': { start: '10:00', end: '18:00' },
      'Sat 10 Oct': { start: '10:00', end: '18:00' },
      'Sun 11 Oct': null,
    },
  },
];

export const initialCompanySettings: CompanySettingsData = {
  companyName: 'Bella Hair Salon',
  street: 'Musterstrasse 1',
  postalCode: '9000',
  city: 'St. Gallen',
  country: 'Switzerland',
  state: 'St. Gallen',
  industry: 'Hair & Beauty',
  businessPhone: '+41 71 000 00 00',
  currency: 'Swiss Franc - CHF',
  branchLanguage: 'English',
  timeZone: 'Europe/Zurich (GMT+01:00)',
  description: 'Tell customers about your salon...',
  website: 'https://www.bellahair.ch',
  facebook: 'facebook.com/bellahair',
  xProfile: 'x.com/bellahair',
  instagram: 'instagram.com/bellahair',
  legalNote: 'https://www.bellahair.ch/legal',
  customTerms: false,
};

export const initialBookingHours: BookingHoursDay[] = [
  { day: 'Monday', isOpen: true, from: '09:00', to: '18:00' },
  { day: 'Tuesday', isOpen: true, from: '09:00', to: '18:00' },
  { day: 'Wednesday', isOpen: true, from: '09:00', to: '18:00' },
  { day: 'Thursday', isOpen: true, from: '09:00', to: '18:00' },
  { day: 'Friday', isOpen: true, from: '09:00', to: '18:00' },
  { day: 'Saturday', isOpen: false, from: '09:00', to: '18:00' },
  { day: 'Sunday', isOpen: false, from: '09:00', to: '18:00' },
];
